{
 "title": "节点基础监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up{}, cluster)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_load1{}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU 使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    1 - \n        avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", mode=\"idle\", instance=\"$instance\"}[2m]))\n)"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n    node_memory_MemAvailable_bytes{instance=\"$instance\"} / node_memory_MemTotal_bytes{instance=\"$instance\"}\n)"
    }
   ]
  },
  {
   "title": "入流量",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{cluster=\"$cluster\", instance=\"$instance\", device=\"eth0\"}[2m]))"
    }
   ]
  },
  {
   "title": "出流量",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{cluster=\"$cluster\", instance=\"$instance\", device=\"eth0\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", mode=\"idle\", instance=\"$instance\"}[2m])) by (cpu))",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "平均负载(5m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$instance\"}) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均负载(15m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$instance\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "系统盘使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n    node_filesystem_avail_bytes{cluster=\"$cluster\", instance=\"$instance\", mountpoint=\"/\"} /\n    node_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\", mountpoint=\"/\"}\n)"
    }
   ]
  },
  {
   "title": "剩余内存",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "当前空间使用情况",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}"
    },
    {
     "expr": "1 - \n(\n    node_filesystem_avail_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}\n    /\n    node_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}\n)"
    }
   ]
  },
  {
   "title": "当前 inode 使用情况",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_files_free{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}"
    },
    {
     "expr": "node_filesystem_files{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}"
    },
    {
     "expr": "1 - \n(\n    node_filesystem_files_free{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}\n    /\n    node_filesystem_files{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}\n)"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\"} + node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_SReclaimable_bytes{instance=\"$instance\"}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_Buffers_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_SReclaimable_bytes{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "存储", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "磁盘空间使用情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"} - node_filesystem_free_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用量"
    },
    {
     "expr": "(node_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"} - node_filesystem_free_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}) /\nnode_filesystem_size_bytes{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用率"
    }
   ]
  },
  {
   "title": "磁盘 inode 使用情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_files{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"} - node_filesystem_files_free{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用量"
    },
    {
     "expr": "(node_filesystem_files{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"} - node_filesystem_files_free{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}) /\nnode_filesystem_files{cluster=\"$cluster\", instance=\"$instance\", fstype!~\"nfs.*|tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用率"
    }
   ]
  },
  { "title": "计算", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU/内存 使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n1 - \n    (\n      node_memory_MemAvailable_bytes{cluster=\"$cluster\", instance=\"$instance\"} / \n      node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=\"$instance\"}\n    )\n)",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", mode=\"idle\", instance=\"$instance\"}[2m])))",
     "legendFormat": "CPU 使用率"
    }
   ]
  },
  {
   "title": "CPU 使用率(单核)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", mode=\"idle\", instance=\"$instance\"}[2m])) by (cpu))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "平均负载",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "node_load1{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "node_load5{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "node_load15{cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "CPU 使用率明细",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\", mode!=\"idle\"}[2m])) by (instance, mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}