{
 "title": "节点 Pod 监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up{}, cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\", internal_ip!=\"169.254.128.10\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "内存分配率",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"memory\", node=\"$node\"}) by (node)\n/\non (node) group_left kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU 分配率",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\", node=\"$node\"}) by (node)\n/\non (node) group_left kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Pod 数量与状态分布",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{cluster=\"$cluster\"} * on (namespace, pod) group_left(node) kube_pod_info{cluster=\"$cluster\", node=\"$node\"}) by (phase) > 0",
     "legendFormat": "{{phase}} 数量"
    }
   ]
  },
  {
   "title": "异常 Pod 列表",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{cluster=\"$cluster\"} * on(namespace, pod) group_left(node) kube_pod_info{cluster=\"$cluster\", node=\"$node\"}) by (namespace, pod, reason) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Request 分布",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", node=\"$node\", resource=\"cpu\", unit=\"core\"}) by (namespace, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Request 分布",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", node=\"$node\", resource=\"memory\", unit=\"byte\"}) by (namespace, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU 使用量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container!=\"\"}[2m])) by (namespace, pod) * on (namespace, pod) group_left(node) kube_pod_info{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cluster=\"$cluster\", container!=\"\"} * on (namespace, pod) group_left(node) kube_pod_info{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}