{
 "title": "Pod 监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!~\"|sandbox\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU 使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "cpu 使用量"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", contianer=~\"$container\"}[$__rate_interval])) by (container) /\non (container) group_left kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\", unit=\"core\", contianer=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", contianer=~\"$container\"} /\non (container) group_left kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\", unit=\"byte\", contianer=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU 使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!~\"|sandbox\", container!=\"\"}[$__rate_interval])) by (container) ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU 限流",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])\n) by (container) /\nsum(\n    increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "$container 容器CPU占用明细",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "repeat": "container",
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!~\"|sandbox\", container=~\"$container\"}[$__rate_interval])",
     "legendFormat": "总 CPU 占用"
    },
    {
     "expr": "irate(container_cpu_user_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!~\"|sandbox\", container=~\"$container\"}[$__rate_interval])",
     "legendFormat": "用户态占用"
    },
    {
     "expr": "irate(container_cpu_system_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!~\"|sandbox\", container=~\"$container\"}[$__rate_interval])",
     "legendFormat": "内核态占用"
    }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "WSS 内存占用(不含Cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"})",
     "legendFormat": "Pod 内存占用"
    }
   ]
  },
  {
   "title": "总内存占用(含Cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}